---
apiVersion: v1
kind: Namespace
metadata:
  name: envepop-api
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: envepop-api
  namespace: envepop-api
  labels:
    k8s-app: envepop-api
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: envepop-api
  template:
    metadata:
      labels:
        k8s-app: envepop-api
        name: envepop-api
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: alpine:3.10
        name: envepop-api
        ports:
        - name: http
          containerPort: 8001
        resources:
          requests:
            cpu: "256m"
            memory: "512m"
---
kind: Service
apiVersion: v1
metadata:
  name: envepop-api
  namespace: envepop-api
spec:
  selector:
    k8s-app: envepop-api
  ports:
    - protocol: TCP
      port: 8001
      name: web
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: envepop-api
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: envepop-api
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service: 
            name: envepop-api
            port:
              number: 8001

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: envepop-api
  namespace: envepop-api
spec:
  maxReplicas: 3
  minReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: envepop-api